framework:
    cache:
        pools:
            cache.rate_limiter:
                adapter: cache.adapter.apcu

when@test:
    framework:
        cache:
            pools:
                cache.rate_limiter:
                    adapter: cache.adapter.array
