framework:
    secret: '%env(APP_SECRET)%'
    handle_all_throwables: true
    http_method_override: false
    session: false
    router:
        utf8: true
    php_errors:
        log: true
    serializer:
        enabled: true
    validation:
        enabled: true

when@dev:
    framework:
        assets: ~
