monolog:
    handlers:
        main:
            type: stream
            path: "php://stdout"
            level: '%env(default:log_level_default:LOG_LEVEL)%'
            formatter: monolog.formatter.json
