services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    env_file: .env
    volumes:
      - .:/var/www/html
      - ./config/private-key-agent.yaml:/etc/private-key-agent/config.yaml:ro
      - ./docker/app.dev.ini:/usr/local/etc/php/conf.d/zz-app-local.ini:ro
    ports:
      - "80:80"
    restart: unless-stopped
