services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
    volumes:
      - .:/app
      - ./config/private-key-agent.yaml:/etc/private-key-agent/config.yaml:ro
      - ./docker/app.dev.ini:/usr/local/etc/php/conf.d/app.ini:ro
      - ./docker/Caddyfile:/etc/frankenphp/Caddyfile:ro
    ports:
      - "443:443"
    restart: unless-stopped
